### PR TITLE
ENH:  Initial commit.

### PR DESCRIPTION
**Pull request by ntustison**
This isn't necessarily for inclusion.  I had done some work integrating the new ``MeasureImageSimilarity`` into ANTsR thinking that this would be useful for a particular project but I decided to not work through ANTsR for now.  However, I didn't want to delete what I had done so I'm putting it here.  This commit is not going to pass because ``MeasureImageSimilarity`` not included in the ANTs core apps.

### CODE REVIEW

**Comment by stnava** [comment]
@ntustison .... is this just making a ants commit to include MeasureImageSimilarity in the ants core apps? would be very useful to have around.

**Comment by ntustison** [comment]
I was putting together an R [interface](https://github.com/stnava/ANTsR/pull/167/files#diff-ff12fb54ac1d671c83463ca21b710123) for ``MeasureImageSimilarity.cxx`` but that would require putting it in the ants core apps.  I figured that I would let people use it a bit before pulling the trigger on the necessary changes.  Are you up for making those changes now?

**Comment by stnava** [comment]
not up for it it now - let's give it a month, roughly

**Comment by ntustison** [comment]
Sounds good.

**Comment by stnava** [comment]
superceded by jeff's recent `imageSimilarity` commit.

**Pull request closed without merging**
