### PR TITLE
Adding resampleImageToTarget

### PR DESCRIPTION
**Pull request by dorianps**
Added a new function to resample an image based with the same resolution and header as a target image. This resolves an error observed when downsampling an image and upsampling it back to the same size, which causes the voxels to be of slightly different size, causing some functions (i.e., labelStats) to see the images as occupying different physical spaces.

### CODE REVIEW

**Comment by jeffduda** [comment]
This should be fairly easy to do with the antsTransform functions, i.e:

newImage <- antsTransformApplyToImage(
transform=antsTransformCreate(type="AffineTransform"), image=inputImage,
reference=referenceImage)

**Comment by stnava** [comment]
@jeffduda i agree ... but `antsApplyTransforms` may not yet work with this transform type.   i also do not see a function called `antsTransformApplyToImage` ... if such a function exists, it should be renamed.  perhaps just `applyAntsrTransform` and make it general enough to work on images and points.   obviously, this new transform stuff will lead to some confusion.  we should try to work this out systematically before we start using it extensively.

**Comment by jeffduda** [comment]
sorry, that should have said antsApplyTransformToImage. I can make a
wrapper function such as applyAnts(r?)Transform that takes various data
types and applies the correct transform routine.

**Comment by stnava** [comment]
ok - that wrapper function sounds good.

we should clarify somewhere in documentation that the ants transforms are
on disk and antsr transforms are antsr "objects" or pseudo-objects.

thus the different names.

am open to other ideas though.


brian

**Comment by dorianps** [comment]
To @jeffduda @stnava 
How is this going. Did you guys decide what is the best option for this function? @jeffduda was about to try which one is faster I think, resampling or applying transforms.

**Pull request closed without merging**
