### PR TITLE
New versions of vwnrfs,mrvnrfs, and adding randomMask

### PR DESCRIPTION
**Pull request by dorianps**
This provides a rewrite of vwnrfs and mrvnrfs to handle individual labelmasks and occupy less memory. All crucial processing is now performed by vwnrfs alone, and mrvnrfs is a wrapper to vwnrfs functionality with no direct processing of images to feed to vwnrfs.

### CODE REVIEW

**Comment by stnava** [comment]
see the automated comments above  ( red X next to your commits).   the conflicts prevent merging, testing etc.   i recommend you merge the master branch from ANTsR into your fork and resolve conflicts.   or create a new fork.   read this closely for further direction: https://help.github.com/articles/syncing-a-fork/

**Comment by dorianps** [comment]
Did that, should be good to go now. There is also resampleImageToTarget in here though.

**Comment by stnava** [comment]
if you look at the part of the pull request that reads "All checks have
faile
​d"​ then you will see that the conflicts still exist and are preventing
merging, testing etc.

if look at the "Details" section, you will see the travis build results.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/102993649/log.txt

They show:

** R
Error in parse(outFile) :
  /home/travis/build/stnava/ANTsR.Rcheck/00_pkg_src/ANTsR/R/mrvnrfs.R:156:1:
unexpected input
155: #' @export mrvnrfs.predict
156: <<
     ^
ERROR: unable to collate and parse R files for package â€˜ANTsRâ€™


This means that the conflicts have not been resolved.  It's often fairly
easy for the code author to resolve these just be searching for the
conflicts and choosing the right parts of code, while deleting the rest.

To fix this:

(1) resolve conflicts

(2) make sure the new version of your antsr installs correctly and examples
run

(3) update the pull request

(4)  check the travis build/test results.

if all that is good, then this should merge cleanly with base antsr.


brian

**Comment by stnava** [comment]
if you cant identify the source of your conflicts, then you can just email me the files and i can do this manually ... otherwise, just make a new pull request from a clean branch

**Pull request merged**
