### PR TITLE
trying to create the overloaded operators

### PR DESCRIPTION
**Pull request by muschellij2**
This needs to be checked (takes a long time on my machine).  Overall, though, I'm trying to overload the operators so you don't have to do things like `%%.antsImage` definitions in your code, but use the Ops methods already available (and Math).

### CODE REVIEW

**Comment by muschellij2** [comment]
You would have to tweak some of the operations so that it would work for `signature(e1 = "antsImage", e2 = "antsRegion")`, but that'd still probably be more robust code than the current implementation.

**Comment by muschellij2** [comment]
Any progress???

**Comment by stnava** [comment]
is this ready to be merged, travis passes?


brian

**Comment by muschellij2** [comment]
Passed when I submitted a month ago.  Today it failed with some weird things about NLopt ( I don't think relevant to my added code, just need to rerun, I'm repushing):
https://travis-ci.org/stnava/ANTsR/jobs/228407647

**Comment by stnava** [comment]
am going to just risk this merge -  let's see how it goes

**Comment by stnava** [comment]
This commit breaks image subsetting.

probably easier for you to re-add some piece of code that was removed.

**Comment by stnava** [comment]
i reverted this commit from master and placed to a new branch where you might experiment more freely

https://github.com/stnava/ANTsR/tree/testNewOperators

**Pull request merged**
