### PR TITLE
Updated using the new travis.sh

### PR DESCRIPTION
**Pull request by muschellij2**
See https://github.com/muschellij2/ghtravis for some of the functions.  Mainly the `install_remote_binaries` function executes the latest (with respect to creating date) installation of the binary packages.

### CODE REVIEW

**Comment by muschellij2** [comment]
Also, given this new function, if we use `travis_helpers.sh`, then we don't need to do the `latest` tagging that you do here.

**Comment by stnava** [comment]
not sure why osx is so slow - merging based on linux success

**Comment by stnava** [comment]
can you explain further?

i just put the latest stuff up to provide bleeding edge testing/not
official release.

does this obviate that need?


brian

**Comment by muschellij2** [comment]
You just need to tag the commit.  The `ghtravis::install_remote_binaries(remotes = c("stnava/ANTsR"))` will install the latest binary.  In `travis_helpers.sh`, the `remote_binary_install` will install the binaries for all remotes if available.  It will delete the remotes in the DESCRIPTION file if the package installs and the version is `>=` the one specified in the `DESCRIPTION`.  If not, the remote is kept and will be installed via `install_github(..., dependencies = FALSE)`.

**Comment by muschellij2** [comment]
So you just need to tag and push the current commit to make binaries.

**Comment by muschellij2** [comment]
So whenever you tag (which only be major updates/stable-ish things, if you tag - then it should make a release which we can grab from the GitHub API.

**Pull request merged**
