### PR TITLE
moving to %doMath% from iMath

### PR DESCRIPTION
**Pull request by armaneshaghi**
I propose this change to make sequential math operations easier. Similar to arithmetic operators by @bkandel that allows using `+`, `-`, `*`, and `/` between images, I have used functional programming style of infix functions  for this. So for example, instead of `iMath(iMath(fi, "Normalize"), "Laplacian", 1, 1) - (iMath(fi, "Normalize")) * -1`
 we can do `fi %doMath% "Normalize" %doMath% "Laplacian 1 1" - (fi %doMath% "Normalize" ) * -1`. 

This new change allows easier use of multiple mathematical operation in addition to intuitive integration with arithmetic operation. In general moving to [functional programming](http://adv-r.had.co.nz/Functional-programming.html) will make the life of our users easier.

Vignettes for this are also included.

Known problem:

 - Since I have used infix functions, it was difficult to find a way to use `LabelStats` that comes with an `antsImageClass` instead of characters as parameters. I will find a way to integrate this, or perhaps we can introduce another function for this.

Next steps:
 - I think we should gradually phase out `ImageMath` and `iMath`. This PR however does not remove any file or function. I will leave this for you to decide.

### CODE REVIEW

**Comment by stnava** [comment]
arman - this looks great and i am all for it ... let me review this before
we commit to it ... i have a few other things to finish up before i get to
look it over ... am also interested in @bkandel 's opinion ...

longer term, i hope we can use  %iMath% instead of %doMath%  .... i am just
partial to that name ....


brian

**Comment by bkandel** [comment]
Looks cool.  I'll play around with it a bit and let you know how it goes
for me.

**Comment by armaneshaghi** [comment]
no problem with the name, the only reason was not to conflict. If we decide on the final fate of current iMath I will rename it to `%iMath%`.

**Comment by stnava** [comment]
great - this is a potentially fantastic contribution ... but let's move
slowly b/c lots will have to change in the documentation, scripts etc for
this to integrate smoothly.


brian

**Comment by bkandel** [comment]
I think this looks great.  I am a bit hesitant, though, because it doesn't
let you specify parameters, e.g. iMath(img=a, operation='MD', param=3) and
so makes code harder to read and more confusing for beginners.  There's a
reason that the only infix functions that R provides are binary operators.

In any case, this function could just be called %iMath% and should probably
be very lightweight:
%imath% <- function(img, params){
  mysplit <- strsplit(params, ' ')
  oper <- mysplit[1]
  param <- c(mysplit[2:length(mysplit)])
  iMath(img, oper, param)
}

or something along those lines.  %iMath% should not re-do the work of
iMath.  I don't see a problem with having both iMath and %iMath%, but for
the reasons above, I'd be wary of totally getting rid of iMath.

**Comment by stnava** [comment]
@bkandel agree that having both is fine and useful ...  @armaneshaghi - any
reason that iMath and %iMath% could not coexist?


brian

**Comment by stnava** [comment]
perhaps %o%  would be better ... fewer characters = easier to read


brian

**Comment by armaneshaghi** [comment]
thanks for the comments, I will make it just part of `iMath`, instead of a replacement. I still need to change vignettes, hopefully will do this today.

**Comment by bkandel** [comment]
%o% is outer product though.

**Comment by stnava** [comment]
dplyr uses  %.%   ...  maybe it would be best to stick with that - assuming
it can be overridden for our use cases
>
>

**Comment by jefferis** [comment]
dplyr `%.%` is deprecated in favour of `%>%`, which comes from magrittr  (see https://github.com/hadley/dplyr/commit/67183e2771f24f59330fdaae1bb58b627a58a8ff).

Both chain/pipe operators have the basic function of inserting the previous result into the first argument of the next expression. There are also special syntax rules that could be useful. The operators could work as is, if you defined functions for your iMath

e.g. rather than

```
fi %doMath% "Normalize" %doMath% "Laplacian 1 1" - (fi %doMath% "Normalize" ) * -1
```
```
fi %>% Normalize
  %>% Laplacian(1, 1)
  %>% - (fi %>% Normalize ) * -1
```
Personally, I might hesitate to overload the %>% operator if the syntax were very different from its usage in other contexts.

**Comment by armaneshaghi** [comment]
thanks@jefferis, 

@stnava @bkandel   with this we  can pass parameters. so all the functionality of `iMath` could potentially be transferred to this new function (whatever we decide to call it )

**Comment by stnava** [comment]
hmm ... this looks even better ... readability wise and for
consistency with other parts of R.    to me, this seems like the right
answer ... i.e. achieving this:

```
fi %>% iNormalize
  %>% iLaplacian(1, 1)
  %>% - (fi %>% iNormalize ) * -1
```

in terms of implementation see :

Documenting multiple functions in the same file

at

http://r-pkgs.had.co.nz/man.html

which points the way ... we can call iMath inside each of these
functions s.t. they are just lightweight wrappers ... recall that the
whole reason for iMath is just to reuse the existing c++
infrastructure / reduce maintenance.   however, this structure will
also let us define small / lightweight functions that dont rely on
iMath e.g.   image binding:

```
ibind<-function( img1, img2 ) {
  imgbind<-as.antsImage( abind::abind(as.array(img1), as.array(img2)) )
  antsCopyImageInfo(img1,imgbind)
  }
```
if i am understanding correctly, this would give us

```
fi %>% ibind( img2 ) %>% iNormalize
```

brian

**Comment by stnava** [comment]
yes - i think this is good advice and we should follow it ...


brian

**Comment by bkandel** [comment]
This also looks even better to me.  We should probably aim to base our
implementation off of tidyr and magrittr so that our package is easy to use
for users of those packages.

**Comment by stnava** [comment]
thanks to @jefferis and @armaneshaghi  , we have a clearer and easier way to chain operations together:  
```
fi<-antsImageRead( getANTsRData("r16") , 2 )
plot( fi %>% iMath("Laplacian",1)  %>% iMath("GD",3) )
```

or 
```
multismoo<- fi %>% iBind( smoothImage(fi,2) ) %>% iBind( smoothImage(fi,4) )
```
but this induces a dependency on `magrittr` - maybe not that bad ... 

also added this "problem" scenario ...

```
fi<-antsImageRead( getANTsRData("r16") , 2 )
rflct<-iMath(fi,"ReflectionMatrix",1)
tt<-antsApplyTransforms(fi,fi,rflct)
plot(tt)
```

**Comment by jefferis** [comment]
On 24 Feb 2015, at 23:15, stnava <notifications@github.com> wrote:

> but this induces a dependency on magrittr - maybe not that bad ...

Better than rolling your own pipe operator I'd say. It's a lightweight dependency and, since it's required for dplyr, r studio will look after it if necessary or provide a replacement long term. dplyr is everywhere these days so soon most users will have magrittr on their machines anyway. 

Best,

Greg.

**Comment by armaneshaghi** [comment]
I will close this PR as Brian has already did the work, the vignettes however may be useful for another PR.

**Comment by stnava** [comment]
yes - i think the vignettes should be revisited w/the new style ...

**Pull request closed without merging**
