### PR TITLE
Added basic RFT functions

### PR DESCRIPTION
**Pull request by Tokazama**
This contains some new functions for performing an RFT analysis:

* euler: calculates euler characteristic
* rftResults: given certain parameters calculates set, cluster, and peak level statistics
* rftPval: basic formula that is utilized for RFT p-values
* statFieldThresh: various methods of thresholding a statistical field
* resels: estimates resolution elements
* estSmooth: estimates the FWHM

I have included documentation for each but I haven't roxygenised them.

### CODE REVIEW

**Comment by stnava** [comment]
do you mind running roxygen2::roxygenize() inside of the ANTsR directory and then adding the result to this pull request?  i'd like to see the R CMD check results on travis.

**Comment by Tokazama** [comment]
I've never really run roxygenize before, so I might be doing something wrong. When I run it I get a bunch of warnings on the antsImage_class and antsImageIterator_class files saying "requires name and description".

**Comment by Tokazama** [comment]
Sorry for the messy commits. It took me a bit to figure out the travis checks while bouncing back and forth between computers.

**Comment by stnava** [comment]
looks good ... one minor issue:

```

Undocumented arguments in documentation object 'statFieldThresh'
  â€˜reselsâ€™ â€˜threshTypeâ€™
Documented arguments not in \usage in documentation object 'statFieldThresh':
  â€˜threshType:â€™ â€˜maskâ€™
```

please address and i will merge.

**Comment by stnava** [comment]
Sorry I lost track of this ... It looks close enough to merge.   Thank you much!  Please keep us updated if you find bugs or want to add functionality.

**Pull request merged**
