### PR TITLE
Landmark transform

### PR DESCRIPTION
**Pull request by zarquon42b**
I  added functions ```points2LabelImage```, ```landmarkTransform``` and  ```transform2mat``` 

to 
* create label images from point sets
* compute and dump affine transform from landmarks 
*  write affine transforms to mat format
* updated .travis.yml

### CODE REVIEW

**Comment by zarquon42b** [comment]
OK, it seems one has to whiltelist https://launchpad.net/~marutter/+archive/ubuntu/c2d4u and install r-cran-rcppoctave to satisfy travis

**Comment by zarquon42b** [comment]
About the travis issue: as you switched to the container based testing, we have to wait until ppa:octave/stable has been whitelisted. (see https://github.com/travis-ci/apt-source-whitelist/issues/53)

**Comment by stnava** [comment]
Thx for update.  let me know when white listing happens ... Would be great
to have these features in AntsR.

**Comment by stnava** [comment]
also - unfortunately, we do need the containers because otherwise we exhaust memory, time or both during ANTsR (+dependencies) install / compile

**Comment by zarquon42b** [comment]
Maybe switch to travis' new trusty beta, you get 7.5 gig RAM there: http://docs.travis-ci.com/user/ci-environment/ . However, cache is not available there. But maybe use the cran2deb4ubuntu repo to avoid compiling of package dependencies (if available).

**Comment by stnava** [comment]
not sure this would resolve issues with compilation/install time  ... happy to be proven wrong.

**Comment by zarquon42b** [comment]
So travis just makes it under the time limit (but much slower than the container based version). Maybe wait until the containers move to trusty too, hopefully octave will be available then.
Anyway,  If you do not want to risk it with the prolonged time, the functions are also available on my apocryphous package [RANTs](https://github.com/zarquon42b/RANTs).

**Comment by stnava** [comment]
thanks for checking this out stefan ... we were, in the past, bumping right
around the time limit and that ends up being unstable due to bandwidth
effects.

so we'll put this on hold for now.


brian

**Comment by zarquon42b** [comment]
As an older version of RcppOctave seems to build with precise's octave version (octave3.2-headers), I applied for this deb package to get whitelisted (more likely than to get the octave/stable ppa whitelisted) and then use the older version for testing.

**Comment by stnava** [comment]
@jeffduda is contributing this: https://github.com/stnava/ANTsR/blob/antsTransform/vignettes/antsTransform.Rmd 

any comments appreciated

**Comment by zarquon42b** [comment]
Obsoleted by native support of itkTransforms

**Pull request closed without merging**
