### PR TITLE
ENH:  Add blood perfusion calculation.

### PR DESCRIPTION
**Pull request by ntustison**
Hey @stnava , this is the blood perfusion calculation stuff I've been talking about.

### CODE REVIEW

**Comment by muschellij2** [comment]
For colAvg and rowAvg can use colMeans and rowMeans, with NA options, as
well as colSums and rowSums, which is much faster than apply.
I'd also suggest the matrixStats package for colMaxs and rowMaxs which
again is much faster than apply and is written in C (I think)

Hope that helps and thanks for the addition!

**Comment by ntustison** [comment]
Ahh, good to know.  Thanks.  I can get rid of everything except for the colMax function.  I don't know how @stnava feels about including another dependency.  I'll wait until he weighs in before possibly changing that.

**Comment by stnava** [comment]
yeah - another dependency would not seem worth it ... i'd imagine those
lines of code only contribute incrementally to the cost.  if you did want
to speed it up, you could probably compute all those stats within one loop
(or one call to apply).


brian

**Comment by ntustison** [comment]
It seems as though the recommendations @muschellij2 made for the functions already in {base} seemed to speed up the process significantly---not that time was a huge issue to begin with.

**Comment by stnava** [comment]
@ntustison is this ready now?

**Comment by ntustison** [comment]
I believe so.

**Pull request merged**
